In [1]:

# numpy datatypes
# numpy  np.array
import numpy as np

In [2]:
def show_array(arr):
    print('Array:', arr, sep='\n')
    print('Type:', type(arr))
    print('Shape:', arr.shape)
    print('Size:', arr.size)
    print('DType:', arr.dtype)
    print('Length:', len(arr))
    print('Dimension:', arr.ndim)

In [3]:
a=np.array([3,8,2,67,45])
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a.dtype)
print(len(a))

[ 3  8  2 67 45]
<class 'numpy.ndarray'>
(5,)
5
int32
5


In [4]:
b=np.array([[10,11,18,14],[45,22,9,2],[6,5,1,8]])
show_array(b)

Array:
[[10 11 18 14]
 [45 22  9  2]
 [ 6  5  1  8]]
Type: <class 'numpy.ndarray'>
Shape: (3, 4)
Size: 12
DType: int32
Length: 3
Dimension: 2


In [ ]:
# array operation 
#1. item accessing :subscripting ,slicing
#2.item Assignment
#3.item insertion 
#4.item deletion
#5.arthmetic

In [23]:
b

array([[10, 11, 18, 14],
       [45, 22,  9,  2],
       [ 6,  5,  1,  8]])

In [27]:
#b[0][0]
#b[1][1:]
#subsrcipting [1st,2nd,3rd,...,nth dim]
#subsrcipting [1st:1st end:stepsize ,2nd,3rd,...,nth dim]
b[0][0]
b[1,-3:] 
b[:,-2]
b[:,-2:-1]

(3, 4)

In [8]:
print(b[2][0:])
b[2][0:].shape

[6 5 1 8]


(4,)

In [5]:
                # 100  110  130  140
                # 145  122   19   12
                # 16    15   11   18
# 10  11  13  14
# 45  22   9   2
# 6    5   1   8
c=np.array([[[10,100],[11,110],[13,130],[14,140]],
            [[45,145],[22,122],[9,190],[2,12]],
            [[6,16],[5,15],[1,11],[8,18]]])
show_array(c)

Array:
[[[ 10 100]
  [ 11 110]
  [ 13 130]
  [ 14 140]]

 [[ 45 145]
  [ 22 122]
  [  9 190]
  [  2  12]]

 [[  6  16]
  [  5  15]
  [  1  11]
  [  8  18]]]
Type: <class 'numpy.ndarray'>
Shape: (3, 4, 2)
Size: 24
DType: int32
Length: 3
Dimension: 3


In [56]:
print(c[:1,:2,:1])

[[[10]
  [11]]]


In [57]:
print(c[:,1:2,:1])
print(c[-2:,-1:,:1])
print(c[:2,-2:,:1])

[[[11]]

 [[22]]

 [[ 5]]]
[[[2]]

 [[8]]]
[[[13]
  [14]]

 [[ 9]
  [ 2]]]


In [61]:
# item Assignment 
b[1,2]=90
b[0,2]=30
b[1,1]=44
b

array([[10, 11, 30, 14],
       [45, 44, 90,  2],
       [ 6,  5,  1,  8]])

In [62]:
a=([2,4,5,7,9])
a

[2, 4, 5, 7, 9]

In [63]:
# item insertion 
a=np.append(a,80)
a

array([ 2,  4,  5,  7,  9, 80])

In [10]:
np.append(b,[[9,90,80,70]],axis=0)  #axis = 0-> row , 1-> column 


array([[10, 11, 18, 14],
       [45, 22,  9,  2],
       [ 6,  5,  1,  8],
       [ 9, 90, 80, 70]])

In [12]:
np.append(b,[[9],[90],[80]],axis=1)

array([[10, 11, 18, 14,  9],
       [45, 22,  9,  2, 90],
       [ 6,  5,  1,  8, 80]])

In [19]:
# Item Deletion
# del a[-1]  # This won't work
b1 = b.copy()
b1

array([[10, 11, 18, 14],
       [45, 22,  9,  2],
       [ 6,  5,  1,  8]])

In [20]:
np.delete(b1, 0, axis=0)

array([[45, 22,  9,  2],
       [ 6,  5,  1,  8]])

In [21]:
# Arithmetic Operations
b1 - 20

array([[-10,  -9,  -2,  -6],
       [ 25,   2, -11, -18],
       [-14, -15, -19, -12]])

In [22]:
b1 + 20

array([[30, 31, 38, 34],
       [65, 42, 29, 22],
       [26, 25, 21, 28]])

In [23]:
b1 * 10

array([[100, 110, 180, 140],
       [450, 220,  90,  20],
       [ 60,  50,  10,  80]])

In [24]:
b1 / 10

array([[1. , 1.1, 1.8, 1.4],
       [4.5, 2.2, 0.9, 0.2],
       [0.6, 0.5, 0.1, 0.8]])

In [25]:
# Array Manipulation
#####################
# arr.reshape(....)
# arr.astype(...)

# More functions to create array
##################################
## np.array()
## np.arange()  -> array version of range func, also allows float
## np.linspace() -> start, end, no. of items
## np.ones() -> generate all values as '1'
## np.zeros() -> generate all values as '0'
## np.random.random()
## np.random.randint()

In [26]:
b1.reshape(2,6,1)

array([[[10],
        [11],
        [18],
        [14],
        [45],
        [22]],

       [[ 9],
        [ 2],
        [ 6],
        [ 5],
        [ 1],
        [ 8]]])

In [27]:
b1.reshape(2,6)

array([[10, 11, 18, 14, 45, 22],
       [ 9,  2,  6,  5,  1,  8]])

In [28]:
b1.reshape(2,6,1,1)

array([[[[10]],

        [[11]],

        [[18]],

        [[14]],

        [[45]],

        [[22]]],


       [[[ 9]],

        [[ 2]],

        [[ 6]],

        [[ 5]],

        [[ 1]],

        [[ 8]]]])